CREATE DATABASE DB_PRODUTOS

CREATE TABLE TB_PRODUTOS(
	IDPRODUTO INT NOT NULL PRIMARY KEY IDENTITY,
	NOMEPRODUTO VARCHAR(150) NOT NULL,
	DESCRICAOPRODUTO VARCHAR(500),
	IDTIPOPRODUTO INT NOT NULL,
	DATACADASTRO DATE
);

CREATE TABLE TB_TIPO_PRODUTO(
	IDTIPOPRODUTO INT NOT NULL PRIMARY KEY IDENTITY,
	DESCRICAOTIPOPRODUTO VARCHAR(200)
);

ALTER TABLE TB_PRODUTOS ADD CONSTRAINT FK_PRODUTO_TIPOPRODUTO FOREIGN KEY (IDTIPOPRODUTO) REFERENCES TB_TIPO_PRODUTO(IDTIPOPRODUTO);

CREATE TABLE NOTA_PRODUTO(
	IDNOTAPRODUTO INT NOT NULL PRIMARY KEY IDENTITY,
	IDPRODUTO INT NOT NULL,
	NOTA INT NOT NULL
);

INSERT INTO TB_TIPO_PRODUTO VALUES('T.I.');

INSERT INTO TB_PRODUTOS VALUES ('MONITOR', 'LOREM IPSUM', 1, GETDATE());
INSERT INTO TB_PRODUTOS VALUES ('TECLADO', 'LOREM IPSUM', 1, GETDATE());
INSERT INTO TB_PRODUTOS VALUES ('MOUSE', 'LOREM IPSUM', 1, GETDATE());














